### ISSUE TITLE
fastL4 预定义profileL4 字段支持

### ISSUE THREAD

**Issue by zongzw** [f5se/cis-c-docs#76]
增强 fastL4 支持：
* 增加 `profileL4`字段支持能力，
* 支持`layer4`字段发生变化（例如 `any` -> `tcp`，`tcp`-> `any`）
* 保持`virtual type`类型为 `Performance Layer 4`不变，而不是将`virtual type`下发为 `Standard`

测试yaml为：

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: vs-performace-l4
  namespace: default
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true,
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.28.0",
        "id": "vs-performace-l4",
        "cistest15": {
          "class": "Tenant",
          "app-1": {
            "class": "Application",
            "template": "generic",
            "app_svc_vs": {
              "class": "Service_L4",
              "layer4": "tcp",
              "profileL4": { "bigip": "/Common/fastL4_3600s" },
              "virtualAddresses": [
                "10.42.20.117"
              ],
              "snat": "self",
              "virtualPort": 80,
              "pool": "app_svc_pool"
            },
            "app_svc_pool": {
              "class": "Pool",
              "monitors": [
                "icmp"
              ],
              "loadBalancingMode": "least-connections-member",
              "members": [
              {
                "servicePort": 80,
                "serverAddresses": []
              }
              ]
            }
          }
        }
      }
    }
```

要求，在BIG-IP上，
* virtual 绑定 profileL4 `/Common/fastL4_3600s`，
* `virtual type` 为`Performance Layler 4`, 
* `ipProtocol` 为 `TCP`
